### ISSUE TITLE
Unable to launch Perfana Demo site

### ISSUE THREAD

**Issue by jagssonawane** [perfana/perfana-demo#1]
Based on documentation mentioned at https://perfana.medium.com/performance-testing-in-an-agile-world-87a860bd5493, I tried to deploy projects on windows VM. however, perfana site is not working at port 4000. Could you please tell me know what step I am missing. 
![image](https://user-images.githubusercontent.com/24912753/123409230-96340100-d5cb-11eb-8228-9a621891e28d.png)

**Comment by dmoll1974** [comment]
Based on the logs Perfana should be running at port 4000. Are you sure you forwarded the port from your VM to your localhost?
